name: Azure Static Web Apps CI/CD

on:
  repository_dispatch:
    types: [update_config]
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - master

jobs:
  build_and_deploy_job:
    if: github.event.action != 'closed'
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3

      - name: Checkout submodules to latest
        run: git submodule update --init --recursive && git submodule update --recursive --remote

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_RED_TREE_089840F00 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: 'upload'
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: '/' # App source code path
          api_location: '' # Api source code path - optional
          output_location: 'dist/sound-buttons' # Built app content directory - optional
          ###### End of Repository/Build Configurations ######
        env:
          GA_TRACKING_ID: ${{ secrets.GA_TRACKING_ID }}
          ORIGIN: ${{ secrets.ORIGIN }}
          BUTTON_ORIGIN: ${{ secrets.BUTTON_ORIGIN }}
          API: ${{ secrets.API }}
          VERSION: ${{ github.sha }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: web
          path: |
            dist/sound-buttons
          retention-days: 10

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_RED_TREE_089840F00 }}
          action: 'close'
