name: Deploy Cloudflare Worker

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Deploy Cloudflare Worker
    steps:
      - uses: actions/checkout@v3
      - name: install dependencies
        run: 'npm install'
      - name: deploy using wrangler
        run: 'npx wrangler publish worker/worker.js --name sound-buttons --compatibility-date 2022-10-15'
        env:
          # CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
